### ISSUE TITLE
TODO: Implement add_per_file.py

### ISSUE THREAD

**Issue by magarenzo** [magarenzo/Git-Scripts#2]
Running `add_per_file.py` should:

* Add all files one at a time
* Set a simple commit message per file pertaining to that file's name
* Push

Check out [`add_all.py`](https://github.com/magarenzo/Git-Scripts/blob/main/src/add_all.py) as a starting point and feel free to reach out with any questions!

**Comment by nelyanne-v** [comment]
Hello, I'd like to help with this, can I take this issue?

**Comment by magarenzo** [comment]
Hello @nelyanne-v, assigned! Looking forward to your take on this 🚀
